[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--tb=short",
    "--strict-markers",
    "--strict-config",
]
filterwarnings = [
    "ignore::DeprecationWarning:homeassistant.components.http.*",
    "ignore::DeprecationWarning:homeassistant.*",
]
markers = [
    "slow: marks tests as slow",
    "integration: marks tests as integration tests",
]
