name: Release

on:
  release:
    types: [published]

jobs:

  release_zip:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get version number
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/} # Remove refs/tags/
          TAG_NAME=${TAG_NAME#v}            # Remove leading v if present
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Update version number in manifest
        run: |
          python3 /home/runner/work/homeassistant-portainer/homeassistant-portainer/.github/update_version.py --version $TAG_NAME

      - name: Zip portainer dir
        run: |
          cd /home/runner/work/homeassistant-portainer/homeassistant-portainer/custom_components/portainer
          zip portainer.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/homeassistant-portainer/homeassistant-portainer/custom_components/portainer/portainer.zip
          asset_name: portainer.zip
          tag: ${{ github.ref }}
          overwrite: true

  releasenotes:
    name: Prepare releasenotes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install requirements
        run: |
          python3 -m pip install setuptools wheel PyGithub

      - name: Update release notes
        run: |
          python3 /home/runner/work/homeassistant-portainer/homeassistant-portainer/.github/generate_releasenotes.py --token ${{ secrets.GITHUB_TOKEN }} --release yes --tag ${{ github.ref }}
